language: bash

matrix:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.2 # 10.14
    - os: osx
      osx_image: xcode10.1 # 10.13
    - os: osx
      osx_image: xcode9.2 # 10.12

install: true
script: >-
  bash tests/install.sh &&
  source ~/.bashrc &&
  bash tests/validate.sh &&
  bash tests/remove.sh
  
  export REQVER=1.12 &&
  bash tests/version.sh &&
  source ~/.bashrc &&
  bash tests/version-validate.sh &&
  bash tests/remove.sh &&
  unset REQVER
